version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-fullstack
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mynet


  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    networks:
      - mynet
    depends_on:
      - mysql
#
#
#  frontend:
#    build: ./frontend
#    container_name: frontend
#    restart: unless-stopped
#    ports:
#      - "3001:3001"
#    volumes:
#      - ./frontend:/app/frontend
#    networks:
#      - mynet
#    depends_on:
#      - backend