version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    ports:
      - 3306:${DATABASE_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mynet


  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
    command: npm run start:dev

    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - mynet
    depends_on:
      - mysql


  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:4200"
    volumes:
      - ./frontend:/app
    networks:
      - mynet
    depends_on:
      - backend
    command: npm run start -- --host 0.0.0.0

networks:
  mynet:
    driver: bridge
